Repository TYPO3/coding-standards, pull requests merged in 2022-12, with the labels that each got.

#70 [TASK] Change PHP version for PHP CS job
  .github/workflows/continuous-integration.yml
Labels: maintenance

#71 [TASK] Replace deprecated set-output command
  .github/workflows/continuous-integration.yml
Labels: maintenance

#74 [TASK] Include skip-changelog label in semver check
  .github/pr-labeler.yml
Labels: maintenance

#73 [RELEASE] Release of TYPO3 Coding Standards 0.6.0
  CHANGELOG.md
  Documentation/Settings.cfg
  src/Console/Application.php
Labels: skip-changelog

#75 [!!!][TASK] Increase PHP requirements to 8.0+
  .github/workflows/continuous-integration.yml
  composer.json
  tests/Unit/Console/Command/SetupCommandTest.php
  tests/Unit/SetupTest.php
  tests/Unit/Smoke/AbstractCliTestCase.php
Labels: maintenance, breaking

#78 [TASK] Remove Composer v1 tests
  .github/workflows/continuous-integration.yml
Labels: maintenance

#77 [!!!][TASK] Remove deprecated commands
  src/Console/Application.php
  src/Console/Command/SetupExtensionCommand.php
  src/Console/Command/SetupProjectCommand.php
  tests/Unit/Console/Command/SetupExtensionCommandTest.php
  tests/Unit/Console/Command/SetupProjectCommandTest.php
Labels: maintenance, breaking

#79 [RELEASE] Release of TYPO3 Coding Standards 0.7.0
  CHANGELOG.md
  src/Console/Application.php
Labels: skip-changelog

#80 [TASK] Set TYPO3 Coding Standards version to 0.8.0
  Documentation/Settings.cfg
  composer.json
  src/Console/Application.php
Labels: maintenance, skip-changelog

#81 [TASK] Add TYPO3 Code of Conduct
  CODE_OF_CONDUCT.md
Labels: maintenance

#83 [BUGFIX] Require a PHP-CS-Fixer version that support the PER standard
  .github/workflows/continuous-integration.yml
  composer.json
Labels: bug

#85 [BUGFIX] Restore PHP 7.2 compatibility
  .github/workflows/continuous-integration.yml
  composer.json
  src/CsFixerConfig.php
  tests/Unit/CsFixerConfigTest.php
Labels: bug

#87 [RELEASE] Release of TYPO3 Coding Standards 0.7.1
  CHANGELOG.md
  src/Console/Application.php
Labels: skip-changelog
