Repository TYPO3/coding-standards, pull requests merged in 2024-01, with the labels that each got.

#118 [TASK] Reformat default PHP-CS-Fixer configuration
  templates/extension_php-cs-fixer.dist.php
  templates/project_php-cs-fixer.dist.php
Labels: maintenance

#117 [BUGFIX] Skip system/settings.php
  src/CsFixerConfig.php
Labels: bug

#121 [TASK] Update CI
  composer.json
  rector.php
  src/CsFixerConfig.php
  tests/Unit/Console/Command/CommandTestImplementation.php
  tests/Unit/CsFixerConfigTest.php
  typo3-coding-standards
Labels: maintenance

#119 [FEATURE] Add support for Symfony v7 components
  composer.json
  src/Console/Command/SetupCommand.php
  src/Console/Command/UpdateCommand.php
  tests/Console/Style/SimpleStyle.php
  tests/Unit/Console/ApplicationTest.php
  tests/Unit/Console/Command/CommandTest.php
  tests/Unit/Console/Command/SetupCommandTest.php
  tests/Unit/Smoke/AbstractCliTestCase.php
Labels: bug, enhancement, maintenance
